### ISSUE TITLE
Errors on download

### ISSUE THREAD

**Issue by PineMaster** [bugsounet/MMM-GoogleAssistant#11]
Umm, I got these errors on the install at electron rebuild
```
An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_                                                                                                             modules/@bugsounet/snowboy/build'
  CXX(target) Release/obj.target/snowboy/lib/snowboy.o
In file included from /home/pi/.electron-gyp/6.1.7/include/node/v8-internal.h:14                                                                                                             ,
                 from /home/pi/.electron-gyp/6.1.7/include/node/v8.h:25,
                 from /home/pi/.electron-gyp/6.1.7/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../lib/snowboy.cc:1:
/home/pi/.electron-gyp/6.1.7/include/node/v8config.h:326:49: warning: ‘Microtask                                                                                                             sCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:8205:3: note: in expansion of mac                                                                                                             ro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/6.1.7/include/node/v8config.h:326:49: warning: ‘Microtask                                                                                                             sCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:8214:3: note: in expansion of mac                                                                                                             ro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
In file included from ../lib/snowboy.cc:1:
../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../../nan/nan.h:2294:62: warning: cast between incompatible function types fr                                                                                                             om ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {ak                                                                                                             a ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../lib/snowboy.cc: In constructor ‘SnowboyDetect::SnowboyDetect(const string&, c                                                                                                             onst string&)’:
../lib/snowboy.cc:38:31: warning: catching polymorphic type ‘class std::runtime_                                                                                                             error’ by value [-Wcatch-value=]
   } catch (std::runtime_error e) {
                               ^
In file included from ../../../nan/nan.h:56,
                 from ../lib/snowboy.cc:1:
../lib/snowboy.cc: At global scope:
/home/pi/.electron-gyp/6.1.7/include/node/node.h:572:43: warning: cast between i                                                                                                             ncompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE                                                                                                             )’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘                                                                                                             void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-                                                                                                             type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.electron-gyp/6.1.7/include/node/node.h:606:3: note: in expansion of ma                                                                                                             cro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../lib/snowboy.cc:183:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(SnowboyDetect, SnowboyDetect::Init)
 ^~~~~~~~~~~
In file included from /home/pi/.electron-gyp/6.1.7/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../lib/snowboy.cc:1:
/home/pi/.electron-gyp/6.1.7/include/node/v8.h: In instantiation of ‘void v8::Pe                                                                                                             rsistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::Wea                                                                                                             kCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCall                                                                                                             backInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]                                                                                                             ’:
/home/pi/.electron-gyp/6.1.7/include/node/node_object_wrap.h:84:78:   required f                                                                                                             rom here
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:9810:16: warning: cast between in                                                                                                             compatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback                                                                                                             ’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’                                                                                                              {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/6.1.7/include/node/v8.h: In instantiation of ‘void v8::Pe                                                                                                             rsistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::Wea                                                                                                             kCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallb                                                                                                             ackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:9810:16: warning: cast between in                                                                                                             compatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’                                                                                                              {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {a                                                                                                             ka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [snowboy.target.mk:143: Release/obj.target/snowboy.node] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_m                                                                                                             odules/@bugsounet/snowboy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-Goog                                                                                                             leAssistant/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                             s.js:248:12)
gyp ERR! System Linux 4.19.118-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-GoogleAssista                                                                                                             nt/node_modules/.bin/node-gyp" "rebuild" "--target=6.1.7" "--arch=arm" "--dist-u                                                                                                             rl=https://www.electronjs.org/headers" "--build-from-source" "--module_name=snow                                                                                                             boy" "--module_path=/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_module                                                                                                             s/@bugsounet/snowboy/lib/node/binding/Release/electron-v6.1-linux-arm" "--remote                                                                                                             _path=./snowboy/v1.4.7/Release/" "--package_name=snowboy-v1.4.7-electron-v6.1-li                                                                                                             nux-arm.tar.gz" "--host=https://github.com/bugsounet/snowboy"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugs                                                                                                             ounet/snowboy
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

Error: make: Entering directory '/home/pi/MagicMirror/modules/MMM-GoogleAssistan                                                                                                             t/node_modules/@bugsounet/snowboy/build'
  CXX(target) Release/obj.target/snowboy/lib/snowboy.o
In file included from /home/pi/.electron-gyp/6.1.7/include/node/v8-internal.h:14                                                                                                             ,
                 from /home/pi/.electron-gyp/6.1.7/include/node/v8.h:25,
                 from /home/pi/.electron-gyp/6.1.7/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../lib/snowboy.cc:1:
/home/pi/.electron-gyp/6.1.7/include/node/v8config.h:326:49: warning: ‘Microtask                                                                                                             sCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:8205:3: note: in expansion of mac                                                                                                             ro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/6.1.7/include/node/v8config.h:326:49: warning: ‘Microtask                                                                                                             sCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:8214:3: note: in expansion of mac                                                                                                             ro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
In file included from ../lib/snowboy.cc:1:
../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../../nan/nan.h:2294:62: warning: cast between incompatible function types fr                                                                                                             om ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {ak                                                                                                             a ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../lib/snowboy.cc: In constructor ‘SnowboyDetect::SnowboyDetect(const string&, c                                                                                                             onst string&)’:
../lib/snowboy.cc:38:31: warning: catching polymorphic type ‘class std::runtime_                                                                                                             error’ by value [-Wcatch-value=]
   } catch (std::runtime_error e) {
                               ^
In file included from ../../../nan/nan.h:56,
                 from ../lib/snowboy.cc:1:
../lib/snowboy.cc: At global scope:
/home/pi/.electron-gyp/6.1.7/include/node/node.h:572:43: warning: cast between i                                                                                                             ncompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE                                                                                                             )’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘                                                                                                             void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-                                                                                                             type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.electron-gyp/6.1.7/include/node/node.h:606:3: note: in expansion of ma                                                                                                             cro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../lib/snowboy.cc:183:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(SnowboyDetect, SnowboyDetect::Init)
 ^~~~~~~~~~~
In file included from /home/pi/.electron-gyp/6.1.7/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../lib/snowboy.cc:1:
/home/pi/.electron-gyp/6.1.7/include/node/v8.h: In instantiation of ‘void v8::Pe                                                                                                             rsistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::Wea                                                                                                             kCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCall                                                                                                             backInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]                                                                                                             ’:
/home/pi/.electron-gyp/6.1.7/include/node/node_object_wrap.h:84:78:   required f                                                                                                             rom here
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:9810:16: warning: cast between in                                                                                                             compatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback                                                                                                             ’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’                                                                                                              {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/6.1.7/include/node/v8.h: In instantiation of ‘void v8::Pe                                                                                                             rsistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::Wea                                                                                                             kCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallb                                                                                                             ackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../nan/nan_object_wrap.h:65:61:   required from here
/home/pi/.electron-gyp/6.1.7/include/node/v8.h:9810:16: warning: cast between in                                                                                                             compatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’                                                                                                              {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {a                                                                                                             ka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [snowboy.target.mk:143: Release/obj.target/snowboy.node] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_m                                                                                                             odules/@bugsounet/snowboy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-Goog                                                                                                             leAssistant/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                             s.js:248:12)
gyp ERR! System Linux 4.19.118-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-GoogleAssista                                                                                                             nt/node_modules/.bin/node-gyp" "rebuild" "--target=6.1.7" "--arch=arm" "--dist-u                                                                                                             rl=https://www.electronjs.org/headers" "--build-from-source" "--module_name=snow                                                                                                             boy" "--module_path=/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_module                                                                                                             s/@bugsounet/snowboy/lib/node/binding/Release/electron-v6.1-linux-arm" "--remote                                                                                                             _path=./snowboy/v1.4.7/Release/" "--package_name=snowboy-v1.4.7-electron-v6.1-li                                                                                                             nux-arm.tar.gz" "--host=https://github.com/bugsounet/snowboy"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugs                                                                                                             ounet/snowboy
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/n                                                                                                             ode_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-GoogleAssis                                                                                                             tant/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/no                                                                                                             de_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_                                                                                                             modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_m                                                                                                             odules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-GoogleA                                                                                                             ssistant/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-GoogleAs                                                                                                             sistant/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/no                                                                                                             de_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-GoogleAssis                                                                                                             tant/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/nod                                                                                                             e_modules/rxjs/internal/Subscriber.js:143:22)
```
also, may I ask what's the difference between this and the other AMk2 (https://github.com/bugsounet/MMM-AssistantMk2/wiki/Usage)

Thanks for making these amazing modules, I rly like them!
:D

**Comment by bugsounet** [comment]
1) This version is not a ready
2) I did not ask to use it!
3) README says: "the simple solution is ... don't use it"
4) Wiki says: "ONLY For My Personal Use!"
5) So I will try to stay nice ...
6) maybe... the solution is resolving the main issue in AMk2 v2 !!!
6) so... go out thanks
