### ISSUE TITLE
config not found issue

### ISSUE THREAD

**Issue by joinsik** [bugsounet/MMM-GoogleAssistant#158]
Can I know what is the problem?

below is the my log...

========================================================================================

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.12.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2020-09-11 23:15:49.913] [LOG]    Starting MagicMirror: v2.12.0
[2020-09-11 23:15:49.959] [LOG]    Loading config ...
[2020-09-11 23:15:49.972] [LOG]    Loading module helpers ...
[2020-09-11 23:15:49.977] [LOG]    No helper found for module: alert.
[2020-09-11 23:15:50.106] [LOG]    Initializing new module helper ...
[2020-09-11 23:15:50.108] [LOG]    Module helper loaded: updatenotification
[2020-09-11 23:15:50.110] [LOG]    No helper found for module: clock.
[2020-09-11 23:15:51.068] [LOG]    Initializing new module helper ...
[2020-09-11 23:15:51.069] [LOG]    Module helper loaded: calendar
[2020-09-11 23:15:51.071] [LOG]    No helper found for module: compliments.
[2020-09-11 23:15:51.073] [LOG]    No helper found for module: currentweather.
[2020-09-11 23:15:51.075] [LOG]    No helper found for module: weatherforecast.
[2020-09-11 23:15:51.165] [LOG]    Initializing new module helper ...
[2020-09-11 23:15:51.166] [LOG]    Module helper loaded: newsfeed
[2020-09-11 23:15:54.010] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/binding/Release/electron-v6.1-linux-arm/snowboy.node'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[2020-09-11 23:15:54.013] [LOG]    Loading module helpers ...
[2020-09-11 23:15:54.014] [LOG]    No helper found for module: alert.
[2020-09-11 23:15:54.015] [LOG]    Initializing new module helper ...
[2020-09-11 23:15:54.016] [LOG]    Module helper loaded: updatenotification
[2020-09-11 23:15:54.017] [LOG]    No helper found for module: clock.
[2020-09-11 23:15:54.018] [LOG]    Initializing new module helper ...
[2020-09-11 23:15:54.018] [LOG]    Module helper loaded: calendar
[2020-09-11 23:15:54.019] [LOG]    No helper found for module: compliments.
[2020-09-11 23:15:54.020] [LOG]    No helper found for module: currentweather.
[2020-09-11 23:15:54.021] [LOG]    No helper found for module: weatherforecast.
[2020-09-11 23:15:54.022] [LOG]    Initializing new module helper ...
[2020-09-11 23:15:54.023] [LOG]    Module helper loaded: newsfeed
[2020-09-11 23:15:54.034] [ERROR]  App threw an error during load
[2020-09-11 23:15:54.035] [ERROR]  Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/binding/Release/electron-v6.1-linux-arm/snowboy.node'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/index.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2020-09-11 23:15:54.038] [ERROR]  Whoops! There was an uncaught exception...
[2020-09-11 23:15:54.039] [ERROR]  Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/binding/Release/electron-v6.1-linux-arm/snowboy.node'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/index.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/lib/node/index.js',
    '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/snowboy/index.js',
    '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[2020-09-11 23:15:54.051] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-09-11 23:15:54.052] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-09-11 23:15:55.058] [LOG]    Launching application.
[2020-09-11 23:16:03.617] [LOG]    Shutting down server...
[2020-09-11 23:16:03.622] [LOG]    Stopping module helper: updatenotification
[2020-09-11 23:16:03.624] [LOG]    Stopping module helper: calendar
[2020-09-11 23:16:03.625] [LOG]    Stopping module helper: newsfeed
[2020-09-11 23:16:03.625] [LOG]    Stopping module helper: updatenotification
[2020-09-11 23:16:03.626] [LOG]    Stopping module helper: calendar
[2020-09-11 23:16:03.627] [LOG]    Stopping module helper: newsfeed

**Comment by bugsounet** [comment]
[closed](https://github.com/bugsounet/MMM-GoogleAssistant/wiki#assume)
