### ISSUE TITLE
Magic Mirror still going blank again

### ISSUE THREAD

**Issue by dhriti-krishna** [bugsounet/MMM-GoogleAssistant#203]
This is the continuation of issue #202 
I updated the A2D and another error occurred
```
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.13.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2021-01-08 17:18:09.847] [LOG]    Starting MagicMirror: v2.13.0
[2021-01-08 17:18:09.855] [LOG]    Loading config ...
[2021-01-08 17:18:09.864] [LOG]    Loading module helpers ...
[2021-01-08 17:18:09.867] [LOG]    No helper found for module: alert.
[2021-01-08 17:18:09.920] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:09.921] [LOG]    Module helper loaded: updatenotification
[2021-01-08 17:18:09.922] [LOG]    No helper found for module: clock.
[2021-01-08 17:18:10.372] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:10.372] [LOG]    Module helper loaded: calendar
[2021-01-08 17:18:10.373] [LOG]    No helper found for module: compliments.
[2021-01-08 17:18:10.375] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:10.376] [LOG]    Module helper loaded: MMM-SmokedMirror
[2021-01-08 17:18:10.377] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:10.378] [LOG]    Module helper loaded: MMM-PiTemp
[2021-01-08 17:18:10.378] [LOG]    No helper found for module: currentweather.
[2021-01-08 17:18:10.379] [LOG]    No helper found for module: weatherforecast.
[2021-01-08 17:18:12.778] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:12.779] [LOG]    Module helper loaded: MMM-GoogleAssistant
[2021-01-08 17:18:12.923] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Could not locate the bindings file. Tried:
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/default/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/compiled/12.4.0/linux/arm/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/release/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/debug/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/default/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/lib/binding/node-v73-linux-arm/epoll.node
[2021-01-08 17:18:12.924] [LOG]    Loading module helpers ...
[2021-01-08 17:18:12.924] [LOG]    No helper found for module: alert.
[2021-01-08 17:18:12.925] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:12.925] [LOG]    Module helper loaded: updatenotification
[2021-01-08 17:18:12.926] [LOG]    No helper found for module: clock.
[2021-01-08 17:18:12.926] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:12.927] [LOG]    Module helper loaded: calendar
[2021-01-08 17:18:12.927] [LOG]    No helper found for module: compliments.
[2021-01-08 17:18:12.927] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:12.928] [LOG]    Module helper loaded: MMM-SmokedMirror
[2021-01-08 17:18:12.928] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:12.929] [LOG]    Module helper loaded: MMM-PiTemp
[2021-01-08 17:18:12.929] [LOG]    No helper found for module: currentweather.
[2021-01-08 17:18:12.929] [LOG]    No helper found for module: weatherforecast.
[2021-01-08 17:18:12.930] [LOG]    Initializing new module helper ...
[2021-01-08 17:18:12.930] [LOG]    Module helper loaded: MMM-GoogleAssistant
[2021-01-08 17:18:12.938] [ERROR]  App threw an error during load
[2021-01-08 17:18:12.939] [ERROR]  Error: Could not locate the bindings file. Tried:
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/default/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/compiled/12.4.0/linux/arm/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/release/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/debug/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/default/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/lib/binding/node-v73-linux-arm/epoll.node
    at bindings (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/bindings/bindings.js:126:9)
    at /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/epoll.js:7:31
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/epoll.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/onoff/onoff.js:5:15)
[2021-01-08 17:18:12.942] [ERROR]  Whoops! There was an uncaught exception...
[2021-01-08 17:18:12.942] [ERROR]  Error: Could not locate the bindings file. Tried:
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Debug/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Release/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/default/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/compiled/12.4.0/linux/arm/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/release/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/debug/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/default/install-root/epoll.node
 → /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/lib/binding/node-v73-linux-arm/epoll.node
    at bindings (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/bindings/bindings.js:126:9)
    at /home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/epoll.js:7:31
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/epoll.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/onoff/onoff.js:5:15) {
  tries: [
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Debug/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/Release/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Debug/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Debug/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/out/Release/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/Release/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build/default/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/compiled/12.4.0/linux/arm/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/release/install-root/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/debug/install-root/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/addon-build/default/install-root/epoll.node',
    '/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/lib/binding/node-v73-linux-arm/epoll.node'
  ]
}
[2021-01-08 17:18:12.953] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2021-01-08 17:18:12.953] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2021-01-08 17:18:13.078] [LOG]    Launching application.

```

**Comment by bugsounet** [comment]
really, i think you don't use the command to update the module
