### ISSUE TITLE
Issue with node auth_and_test.js

### ISSUE THREAD

**Issue by djscottworthing** [bugsounet/MMM-GoogleAssistant#26]
When I run the command node auth_and_test.js, it returns this error:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleAssistant $ node auth_and_test.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'google-assistant'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/auth_and_test.js:7:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I have followed all the steps correctly, running on a RaspberryPi 4 B+

**Comment by bugsounet** [comment]
Hi,
You need install the module, I think you don't do the installation step
